### ISSUE TITLE
Create a Google Doc with application goal and how to achieve the goal

### ISSUE THREAD

**Issue by burrage** [curiouslearning/workshop_drag_into_place_2#8]
Please read the ["Required Assignment" section](https://docs.google.com/document/d/1l1bzJyqzVzCDiqhag1Z6KTSJzd_YotTZaVJD0_f3sWc/edit#heading=h.vonxpxiyh70a) in this document and submit a link in the comments below.

**User Story:**
As a learning literacy instructor,
I want a workshop participant to write out their workshop application’s primary task or goal and how they plan to achieve it,
So that the workshop participant fully understands the educational purpose of their workshop application.

**Acceptance Criteria:**
Given that the workshop participant has read the required readings, has written a Google Doc, and shared the link to the document in the comments,
When I read their Google Doc,
Then I am able to understand the primary goal of their application and how they plan to achieve it.

**Comment by nasilo** [comment]
https://docs.google.com/document/d/1VLOARHCfRFMi-55zLGMnJ3ACI8peHZ6VsrObE5CxSC0/edit?usp=sharing

**Comment by nasilo** [comment]
Adjustments made based on comments
